### ISSUE TITLE
Particle Limit [enhancement]

### ISSUE THREAD

**Issue by koxx12-dev** [isXander/ParticlesEnhanced#2]
mod good but there is one thing that is **annoying** me
i cant have 120380192039 particles on the screen cuz max amount is 20 _and that is very annoying for me_ 
so i would like to suggest a option to **disable that limit**

**Comment by ghost** [comment]
good point

**Comment by isXander** [comment]
It's a multiplier. 20x particles is already too many. More would cause game crashes and the blame would be put on me.
